18F/identity-design-system

package.json, src/css/components/_list.scss
The trailing lines of these bullets were not properly aligned, this fixes that.
=> Update alignment of teal bullets

package.json, src/css/components/_i18n-dropdown.scss
My previous commit had some CSS that was overly greedy and impacted the mobile help dropdown menu... this fixes it 😬
=> Language selector correction

package.json, src/css/_variables.scss, src/css/components/_nav.scss
**Why**:
To prevent text wrapping at specific screen dimensions
=> Added special case for spanish menus to avoid wrapping

docs/_components/alerts.md, docs/_includes/footer.html, docs/brand.md, docs/index.md, src/scss/components/_alerts.scss, src/scss/components/_sidenav.scss
Moved some content around and cleaned up a few styles, things not big enough to capture on the main checklist.
=> moving content around

docs/_components/buttons.md, docs/index.md, src/scss/components/_buttons.scss
=> update button classes

docs/_components/accordions.md, docs/_includes/banner.html, src/scss/components/_buttons.scss, test/components/accordions.test.js, test/dist/scss.test.js
Reverts 18F/identity-style-guide#71
=> Revert "wip - Lg/2.0 accordians"

docs/_components/form-fields.md, docs/examples/basic-header-sidenav-slim-footer.html, docs/examples/extended-header-no-sidenav-medium-footer.html, package-lock.json
update accordion buttons on the form field component
=> update form field accordian buttons

package-lock.json, src/scss/functions/_focus.scss
=> Added argument declaration in _focus.scss for issue #90

docs/_components/alerts.md
This commit adds guidance about when to use alerts to the alert section of the design system
=> LG-1480 Add guidance about using alerts

src/scss/components/_typography.scss
Creates utility class `text-wrap-mixin` that breaks text to new lines for issue #116
=> Added mixin text-wrap for issue 116

docs/content.md
18F content guide and federal plain language guidelines
=> add links to referenced guides

docs/_components/cards.md, package-lock.json, src/scss/components/_cards.scss, src/scss/styles.scss
**Why**: So we can use it to display team info on the dashboard
=> Add a card component

docs/examples/basic-header-sidenav-slim-footer.html, package-lock.json, src/scss/components/_navbar.scss
**Why:** To roll out the search input in the header, the extended-header layout needs some styling updates or revisions
**Preview**
- [Landing page header](https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/nng-lg-2724-extended-header/)
- [Basic header](https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/nng-lg-2724-extended-header/examples/basic-header-sidenav-slim-footer.html)
- [Extended header](https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/nng-lg-2724-extended-header/examples/extended-header-no-sidenav-medium-footer.html)
**AC**
**When reviewing - Suggested**
=> [WIP] LG-2724 - Update extended-header

package-lock.json, package.json
**Why:** The latest and greatest ... for now
=> Bump npm version from 2.2.1 to 2.2.2

docs/_includes/google_analytics.html, docs/_layouts/base.html
**Why**: LG-3176
**How**: added GA partial
=> Add google analytics

.circleci/config.yml, Gemfile.lock, Makefile
Introduced in #147
**Why**: Out of sync with Gemfile
Adds new lint test to verify no uncommitted changes in local working copy after running `bundle install` and `npm install`.
**Why**: Prevent uncommitted changes on install
=> Update out-of-sync Gemfile

CHANGELOG.md, package-lock.json, package.json
Co-Authored-By: Jessica Dembe <17969963+jmdembe@users.noreply.github.com>
=> Prepare 4.0.0 release

CHANGELOG.md, package-lock.json, package.json
For LG-4226 acceptance ("Update Button component in design system")
Following guidance: https://github.com/18F/identity-style-guide#publishing-a-release-to-npm
=> Prepare 5.0.0 release

package-lock.json, package.json
**Why**: Resolve outstanding dependabot alerts
=> Bump dependencies through npm audit fix

CHANGELOG.md, package-lock.json, package.json
Changelog:
>## 6.1.0
>
>### Improvements
>
>- USWDS is upgraded to the latest version, from v2.11.2 to v2.12.1.
>- Whitespace in checkbox and radio label markup will no longer cause the label text to be misplaced.
>- Margins surrounding an external link icon have been increased slightly.
>- Padding and label font size for tile checkboxes and radio buttons have increased slightly.
=> Prepare 6.1.0 release

jest-puppeteer.config.js, package-lock.json, package.json, scripts/pa11y.sh
**Why**:
Fewer dependencies means:
- Faster install times
- Less maintenance overhead
- Smaller vulnerability surface area
- ![+2, -1255 changes](https://user-images.githubusercontent.com/1779930/150848509-302eae6f-7697-4f9c-9502-66d7c3f76f8b.png)
=> Replace "serve" dependency with Ruby built-in static file server

gulpfile.js, package-lock.json, package.json
**Why**:
- Fewer dependencies
- Faster build
```
NODE_ENV=production npm exec gulp build-sass
```
Before|After
---|---
`[10:13:02] Finished 'build-sass' after 6.55 s`|`[10:11:57] Finished 'build-sass' after 2.19 s`
=> Drop cssnano in favor of Sass built-in compression

CHANGELOG.md, package-lock.json, package.json
This PR finalized the release of 6.3.3
=> Release v6.3.3

CHANGELOG.md, package-lock.json, package.json
> ## 9.1.0
>
> ### New Features
> 
> - Add SVG format option for favicon image. ([#424](https://github.com/18F/identity-design-system/pull/424))
> - Add "centered" variant for banner component. ([#429](https://github.com/18F/identity-design-system/pull/429))
> 
> ### Improvements
> 
> - Update styling for Tag component for consistency with U.S. Web Design System. ([#426](https://github.com/18F/identity-design-system/pull/426))
> - Hide collapsed Accordion component content while JavaScript loads. ([#434](https://github.com/18F/identity-design-system/pull/434))
> 
> ### Dependencies
> 
> - Upgrade USWDS from v3.7.1 to v3.8.0 (see [release notes](https://github.com/uswds/uswds/releases/tag/v3.8.0)) ([#425](https://github.com/18F/identity-design-system/pull/425))
=> Prepare 9.1.0 release

CHANGELOG.md, package-lock.json, package.json
- Update styling for Alert component for increased contrast and consistency with U.S. Web Design System. ([#439](https://github.com/18F/identity-design-system/pull/439))
- Update styling for Validation component icons for consistency with U.S. Web Design System. ([#441](https://github.com/18F/identity-design-system/pull/441))
- Update markup for badge component to use U.S. Web Design System icons. ([#442](https://github.com/18F/identity-design-system/pull/442))
- Existing usage will not be affected until the next major release (see "Deprecations").
- Badge component markup has been updated and will be required in the next major release. ([#442](https://github.com/18F/identity-design-system/pull/442))
- Custom alert icons will be removed in the next major release, use U.S. Web Design …
=> Prepare 9.2.0 release
