18F/identity-design-system

- package.json
- src/css/components/_i18n-dropdown.scss
This supports changing the language selector into an actual link rather than a `div` acting as a link - which will be better for accessibility.
> Small a11y tweak for language selectors

- .npmignore
- package.json
To avoid installing dependencies that have known [security vulnerabilities](https://snyk.io/org/18f-wyj/test/github/18F/identity-idp/03ddda51520349041e3c4edcde8141465d5404e2?fromStatus=true) into identity-idp, this moves all of the dependencies of the style guide into `devDependencies` so if `npm install --production` is run on identity-idp, only the necessary `src` files will be added to the application.
`npm run federalist` would be used to install needed dependencies when deploying to federalist, and `npm install` will still continue to install everything when developing locally.
> Only include src directory in npm package

- package.json
Basscss and normalize.css are required for the rest of our stylesheets to work, so rather than relying on the companion site to have those listed as dependencies, always include them when this npm package is included.
Also removed some leftover dependencies and build scripts from cloning cloud.gov version.
> Add required css libraries as dependencies

- .circleci/config.yml
Currently only for running `npm run lint`, this will soon execute tests as well (once they’re written). 
I’ve run this locally with `circleci local execute --job build` to work out the kinks, so hopefully this should run well when Circle CI is enabled on this repo. 
- The installed gems (in `~/.bundler`) and npm’s cache (in `~/.npm`) are stored across runs to increase build speed (as [recommended by `npm ci`](https://docs.npmjs.com/cli/ci.html)).
- I’ve used `ruby:2.5.3-node-browsers` as a base image so we can easily run `jekyll` in the near future and spin up integration tests in headless Chrome.
<details>
<summary>Output of <code>circleci local execute --job build</code>.</summary>
```
➜ circleci local execute --job build
Docker image digest: …
```
> Introduce Circle CI.

- .circleci/config.yml
- .gitignore
- .pa11yci
- Gemfile
- Gemfile.lock
- Makefile
- _config.yml
- package-lock.json
- package.json
- scripts/pa11y.sh
This PR runs [pa11y accessibility tests](http://pa11y.org/) across all URLs generated by Jekyll (as generated by `jekyll-sitemap`) to assert that the style guide and its documentation pages are held to the [WCAG2AA standard](https://www.w3.org/TR/WCAG20/) (the [same as USWDS](https://github.com/uswds/uswds#accessibility)).
Since the documentation here should fully demonstrate all styles in the style guide, this should help sites which implement the style guide to also be accessible — and should help us catch silly mistakes like color contrast issues.
> Introduce accessibility tests.

- src/scss/components/_buttons.scss
- src/scss/uswds-theme/_color.scss
Follow-up to #20.
My mistake here — I used the wrong shades of light blue when creating the secondary button styles which resulted in insufficient contrast.
| Before (bad) | After (good) |
|-------------|--------------|
| ![Screenshot of active buttons with insufficient contrast](https://user-images.githubusercontent.com/14930/50707088-c66b3c00-102d-11e9-98ca-3e4c3e4377fa.png) | ![Screenshot of active buttons with better contrast](https://user-images.githubusercontent.com/14930/50707044-a6d41380-102d-11e9-8391-42870dcccc13.png) |
Thanks to #21, when #20 was merged our [build failed due to insufficient contrast](https://circleci.com/gh/18F/identity-style-guide/15#artifacts/containers/0).
> Fix button conrast for secondary buttons.

- docs/_components/01-index.md
- docs/_components/buttons.md
- docs/_components/form-fields.md
- docs/_components/progress-indicators.md
- docs/_layouts/main.html
- docs/brand.md
- docs/index.md
- docs/layout.md
- docs/typography.md
- src/scss/components/_typography.scss
- src/scss/styles.scss
- src/scss/uswds-theme/_color.scss
- src/scss/uswds-theme/_typography.scss
This introduces typography documentation, the related styles, and updates the existing documentation pages to use the typography styles as required. 
There are minor variances in size and spacing as compared to the Sketch document — I opted to follow the U.S. Web Design System’s font sizing tools instead of setting exact sizing.
It feels like there should be more documentation here, but I’m not sure anything else is required for implementing these styles. Maybe some documentation about when to use `.usa-prose` and when not to? 
[![Screenshot of typography documentation page](https://user-images.githubusercontent.com/14930/50711882-988df380-103d-11e9-9ca3-3988c9cacef0.png)](https://federalist-proxy.app.cloud.gov/preview/18f/identity-style-guide/typography/typography/)
> Introduce typography documentation and styles.

- Makefile
A follow-up to #21.
Test results are written to a temporary directory — we should clean that when running `npm run clean`.
> Remove tmp directory when cleaning.

- docs/_includes/helpers/color.html
- docs/color.md
- src/scss/styles.scss
- src/scss/uswds-theme/_color.scss
This PR adds the Color documentation page. In the process, I uncovered what I believe to be a bug in the US Web Design System, reported at https://github.com/uswds/uswds/issues/2894. I implemented a temporary workaround in this PR. 
[![Screenshot of new Color page](https://user-images.githubusercontent.com/14930/50798736-6253ac80-12a7-11e9-8bb5-dae877671b86.png)](https://federalist-proxy.app.cloud.gov/preview/18f/identity-style-guide/color/color/)
> Add Color documentation.

- docs/_components/tooltips.md
- src/scss/components/_tooltips.scss
A follow-up to #48.
These styles were previously using percentage units relative to the size of the element the tooltip was attached to, which didn’t work very well when I adjusted the size of the container the tooltip was attached to. 
This PR switches the units to avoid positioning errors as the source element changes size. 
Additionally, using `transform: rotate()` causes some style issues, as the coordinate plane is also rotated. I found it to be more straightforward to adjust the border size instead.
> Adjust tooltip documentation, styles.

- docs/_data/nav.yml
- docs/index.md
- docs/usage.md
Adds the Jekyll plugin used in https://github.com/18F/identity-dev-docs/pull/67 as a reference to the usage instructions, and moves the usage instructions to its own page.
I’ll follow-up this PR with extended usage instructions for the **Compiling source files in your build process** section, after I’ve done a basic integration that does so.
[![Screenshot of usage instructions](https://user-images.githubusercontent.com/14930/52582902-48ecd580-2dfc-11e9-8a7a-b28ac544c80c.png)](https://federalist-proxy.app.cloud.gov/preview/18f/identity-style-guide/documentation-updates/usage/)
> Extract usage instructions to page; add plugin.

- src/scss/components/_buttons.scss
- src/scss/components/_inputs.scss
- src/scss/functions/_focus.scss
- src/scss/styles.scss
- src/scss/uswds-theme/_general.scss
Fixes #57.
This PR uses the login.gov color palette for focus rectangles. Additionally, for inputs with rounded edges, uses box shadows instead of outlines to follow the input’s visible edges.
The new styles are based on the existing styles for secure.login.gov:
Here’s what the new styles in this PR look like:
| Before | After |
|-------|-------|
| ![Screenshot of primary navigation before focus style changes](https://user-images.githubusercontent.com/14930/52577895-1db0b900-2df1-11e9-80d8-4189416d750c.png) | ![Screenshot of primary navigation after focus style changes](https://user-images.githubusercontent.com/14930/52578353-1211c200-2df2-11e9-9e32-78ffaa2018b7.png) |
| ![Screenshot of sidebar navigation before focus style changes](https://user-images.githubusercontent.com/14930/52578080- …
> Adjust focus color, shape.

- .gitignore
- Makefile
- docs/usage.md
- gulpfile.js
- package-lock.json
- package.json
- src/scss/functions/_asset-path.scss
- src/scss/styles.scss
- src/scss/uswds-theme/_general.scss
- test/dist/scss.test.js
This PR makes extending the source Sass files easier within any project, and especially easy within Rails projects.
- The source Sass files are copied over to `dist/assets/scss`, including the `uswds` dependency. The paths used within the style guide to include `uswds` are rewritten to reference the local folder, so no dependency issues will appear when this library is used in another build pipeline.
- Anytime `url([something])` is encountered, it is wrapped in `url(asset-path-if-defined([something]))`. The `asset-path-if-defined()` function passes through the path unchanged, unless the `asset-path()` function is also defined (as it is [within the Rails Asset Pipeline](https://guides.rubyonrails.org/asset_pipeline.html#css-and-sass)).
- The `$font-path` and `$img-path` variables are now …
> Simplify usage of scss within Rails.

- docs/_includes/helpers/code-example.html
- docs/_includes/helpers/color.html
- docs/typography.md
- src/scss/components/_code.scss
- src/scss/components/_tooltips.scss
Fixes #56.
This PR changes inline and block code samples to use a gray background, which helps distinguish it from the surrounding text: 
| Before | After | 
|-------|-------|
| ![Screenshot showing no background color on code or pre elements](https://user-images.githubusercontent.com/14930/52492461-3cb40e80-2b97-11e9-8619-9b5411844448.png) | ![Screenshot showing gray background color on code or pre elements](https://user-images.githubusercontent.com/14930/52492423-2a39d500-2b97-11e9-96cb-cc88ee299b7f.png) |
Because this introduces bottom padding on block code samples, it also addresses the scrollbar issue discussed in #56:
> Code styles

- docs/typography.md
- src/scss/components/_typography.scss
Fixes #54.
Two list tweaks:
1. Adds a max-width to list items.
2. Removes the bottom margin from `<ul>` and `<ol>` elements when they are the last item in a container, to prevent excess bottom space (see screenshot).
Additionally, it adds lists to the Typography documentation page, so we can observe the changes:
| Before | After |
|-------|-------|
| ![Screenshot of list items which do not have maximum width constraints and have extra margin-bottom](https://user-images.githubusercontent.com/14930/52427435-e4650a00-2acd-11e9-8702-0ffef9149e2e.png) | ![Screenshot of list items which are constrained by a maximum width, and do not contain extra margin-bottom](https://user-images.githubusercontent.com/14930/52427332-c8616880-2acd-11e9-9f8b-ce5e5b945d0f.png) |
> Add max-width to list items, remove bottom margin.

- src/scss/styles.scss
- src/scss/uswds-theme/_utilities.scss
Fixes https://github.com/uswds/uswds/issues/2894.
This setting enables state utility classes (for example, `.bg-success`), which makes the state style declarations redundant.
> Include state utility classes by enabling them in the U.S. Web Design System.

- docs/_includes/navbar.html
- src/scss/components/_navbar.scss
This fixes the navigation so it displays properly but also cleans up the design to make it a little tighter.
> Fixing navigation

- .pa11yci.js
Now that #49 is fixed, we can remove these exceptions from the tests. :tada:
> Remove elements hidden from accessibility tests.

- docs/_data/nav.yml
- docs/content.md
- src/scss/components/_navbar.scss
This PR addresses the need for #123 
**Why:** By consistently practicing language in an intentional way, we can provide content that supports login.gov users’ needs and improve their experience on our sites and materials.
**How:**
-  Uses [Login.gov Content Guidelines](https://docs.google.com/document/d/1gasSrnvRG7BVB_iK8YUeXteBymhN0u1Ywz7EABNgJh0/edit#heading=h.r8bl0nbf9nug) 🔒as a reference to develop the page
- Adds _Content_ as its own navbar link item to make space for additional tips/guide in the future
- Reduces margin-left/right spacing in navbar to reduce crowding (Related: #126)
**Seeking feedback:**
- If it's easy to scan through the page
- If the order of content is clear
- If there is any typo to correct
> Create a page for content style guide

- src/scss/components/_code.scss
**Why:** To patch a rendering issue identified in [identity-dev-docs' PR #102](https://github.com/18F/identity-dev-docs/pull/102)
**How:** Redefine both `.highlight::before` and `.highlight::after` width from `$block-border-width` to `0`
When reviewed and merged, we will publish a `patch` release to npm
> Patch _code.scss rendering 

- package.json
**Why:** On the [design.login.gov](https://design.login.gov/) landing page, the `2.1.6` release number doesn't accurately reflect the [latest npm package release](https://www.npmjs.com/package/identity-style-guide), which is `2.2.1`, potentially confusing team members. 
**How:** 
- Updated the package.json file
> Documentation: Update package.json to correct the landing page info

- src/scss/components/_buttons.scss
**Why:** The design system has CSS rules for links in forms that override the button styling when we place a button class on links within a form. We need to be able to style links as buttons in forms where we have not only a "Submit" button, but "Delete" and "Cancel" buttons which would fight over being the One True Form Button if we did not make them links.
> LG-2788 add rules for form "link-buttons"

- package.json
**Why**: To be able to import identity-style-guide from another script, it must define a main entrypoint.
Before|After
---|---
`import 'identity-style-guide/dist/assets/js/main';`|`import 'identity-style-guide';`
Example: https://github.com/18F/identity-idp/pull/3957
Reference: https://docs.npmjs.com/files/package.json#main
Compare upstream: https://github.com/uswds/uswds/blob/f7acaf7e09840f4f84b1398c4d30a977cd7fc1e5/package.json#L8
See resolution failure example: https://unpkg.com/identity-style-guide
> Define main entrypoint for use as Node package

- docs/_components/spinner.md
**Why**: Browsers which support srcset can choose amongst given options the most appropriate, including for multiple pixel densities. Since `@2x` is tailored to 2x pixel density, it should ideally only be rendered when the display device has >1 pixel density. Currently, any browser which supports srcset will always show 2x, even if their display is not 2x.
Reference: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Resolution_switching_Same_size_different_resolutions
Preview URL: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-spinner-pixel-density/components/spinner/
`1x` display|`2x` display
---|---
> Update Spinner documentation to recommend appropriate pixel density

- docs/brand.md
**Why:** In the slide deck section, the `#login-design` reference should be updated to `#login-ux` to reflect the latest name (and in my not humble opinion, the best channel in all of TTS Slack)
> Update`#login-design` Slack channel to `#login-ux`

- docs/_components/form-fields.md
- src/scss/components/_inputs.scss
**Why**: For improved alignment with USWDS, to reduce the likelihood of inconsistent error styling.
Relevant USWDS documentation: https://designsystem.digital.gov/components/form-controls/#text-input
Toward LG-3288, this backports the following revisions from IDP:
https://github.com/18F/identity-idp/blob/73c3c13/app/assets/stylesheets/components/_typography.scss#L51-L57
**Open questions:**
- USWDS includes more styling for error messages than what had existed previously with `usa-input--error-message` ([padding, display, font weight](https://github.com/uswds/uswds/blob/22a9eb278196340c3c8909ff5dbeef4ff39756fd/src/stylesheets/elements/form-controls/_global.scss#L54-L59)). Are all of those stylings agreeable, or should we revert back to the original styling? For example, overriding font …
> Replace usa-input--error-message with usa-error-message (LG-3288, LG-3277)

- .circleci/config.yml
- README.md
- jest.config.js
- package-lock.json
- package.json
- test/screenshot.test.js
**Why**: As a contributor to Login Design System, I want to compare visual impact of my changes on documented components prior to merge, so that I can have an increased sense of confidence that my changes will not introduce unexpected regressions.
Notably, this is being considered to help facilitate an upgrade of USWDS to the latest version, which may have unanticipated cascading effects on Login Design System.
**Implementation Notes:**
This builds upon existing testing infrastructure, leveraging support for Puppeteer, Jest, and CircleCI artifacts ([source](https://github.com/18F/identity-style-guide/blob/master/.circleci/config.yml#L36-L40), [documentation](https://circleci.com/docs/2.0/artifacts/)) to generate and store screenshot differences between the local working copy and the live …
> Add basic visual regression testing

- Makefile
Couple small improvements to lockfile validation implemented in #161:
- 2e48906 Only check diffs of lockfiles in lint task
- **Why**: It may be common to run `npm run lint` before committing changes unrelated to lockfiles, which should not fail due to the fact that there are uncommitted changes.
- fe1c664 Ignore scripts in package-lock.json validation npm install
- **Why**: Faster. Especially since this project runs `bundle install` as a postinstall script, which in lockfile validation is redundant with validate-gemfile-lock. Still satisfies purpose of lockfile validation
> Only check diffs of lockfiles in lint task

- src/scss/uswds-theme/_typography.scss
**Why**: The design system assigns `$theme-global-styles-basic: true;` with the intention of assigning basic styles for common base elements, but this does not apply, because the `$theme-global-styles-basic` setting does not exist. It was replaced with three separate variables as part of the USWDS 2.0.0 beta release process:
>- Replaced the `$theme-global-styles-basic` variable with three explicit global styling vars — each set to `false` by default.
>   - `$theme-global-paragraph-styles` applies styling to `p` elements
>   - `$theme-global-link-styles` applies styling to `a` elements
>   - `$theme-global-content-styles` applies styling to `p`, `a`, `h[1-6]`, `ol`, `ul`, and `table` elements
https://designsystem.digital.gov/about/releases/#version-200-beta-6
~This is not quite ready for …
> Fix basic styles setting assignment

- CHANGELOG.md
- src/js/components/dropdownButton.js
- src/js/main.js
Related: #165
The [dropdown button](https://design.login.gov/components/buttons/#dropdown) JavaScript implementation was not previously implemented as a USWDS-conventional component. Because it contained side-effects to initialize a dropdown button on a page, it was excluded from the package in #165, and only available in the `main.js` precompiled JavaScript bundle. This pull request refactors the code to bring it in line with other components.
Incidentally, this also resolves an issue where only one dropdown button could exist on a page.
**Future Work:**
- Button should assign `aria-controls` to complement existing `aria-expanded` ([documentation](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-expanded)).
- >If the element with the `aria-expanded` attribute controls the …
> Implement dropdown button as component

- README.md
- package-lock.json
- package.json
Bumps version in `package.json` and `package-lock.json`.
I assume it'd not always be necessary to create a pull request like this for a release, though a few points of the documented release process were not entirely clear to me, or should be updated to account for the introduction of a `CHANGELOG.md`.
There's an open question as to whether we would want a `CHANGELOG.md` at all, or at least if one or the other of a release notes and `CHANGELOG.md` should be eliminated, since as proposed, they're duplicated and could fall out of sync. The argument for a dedicated changelog file is (a) to simplify role of release manager in understanding the changes for consideration of the SemVer version if separate from the contributors, (b) accountability that all changes are logged by encouraging …
> Prepare 3.0 release

- docs/usage.md
Sprockets needs to be explicitly told about the images to precompile if they're not referenced in the SASS/JS.
Note that this is just the workaround that I came up with for my use case, but if there's a better way please let me know 😄.
> Update Rails usage docs to include Sprockets config

- CHANGELOG.md
- src/scss/components/_navbar.scss
**Why**: This variable was deprecated in USWDS 2.2.0. Using the updated equivalent puts us in a better position to handle a major version bump of USWDS.
**Expected impact:** There is not expected to be a change in behavior with these revisions, as the deprecated variable was defined as pointing to the new variable value.
**References:**
- https://designsystem.digital.gov/about/releases/#version-220
- https://github.com/uswds/uswds/blob/18cd29e/src/stylesheets/core/_deprecated.scss#L20-L21
> Replace deprecated USWDS variable references with updated equivalent values

- CHANGELOG.md
- src/js/components/dropdownButton.js
**Why**: When using the ES module entrypoint, CommonJS "module.exports" and "require" are invalid.
This should only be an issue when using the ES module entrypoint `build/esm/index.js`, and not an issue for CommonJS usage (`build/cjs/index.js`) or the precompiled copy (`dist/assets/js/main.js`).
This was likely missed due to merge timing between #166 and #165.
> Use ESM import/export syntax for dropdown button

- README.md
- docs/_includes/footer.html
- docs/_layouts/base.html
- docs/examples/extended-header-no-sidenav-medium-footer.html
Since we actually use the branch name in the build for robots meta tags, I'm going to wait until this is merged to update Federalist and Github
> Update to make "main" the new default branch (LG-3379)

- docs/brand.md
Removing the reference to an outdated slide deck from design.login.gov - new year, new deck! 🌮
> Remove slide deck reference from design.login.gov.

- test/screenshot.test.js
**Why**: Check for regressions of content which may be collapsed (hidden) by default.
> Toggle hidden content visible for visual regression tests

- _config.yml
**Why**: So that accessibility redirect introduced in #178 does redirect.
> Enable Jekyll redirect plugin

- docs/_components/accordions.md
- docs/_components/alerts.md
- docs/_components/buttons.md
- docs/_components/form-fields.md
- docs/_includes/helpers/base-component.html
**Why**: As someone using the login.gov Design System, I want to know when a component is implemented as an extension of the U.S. Web Design System, so that I can reference guidance from the USWDS documentation, and see specific implementation differences contained in the component stylesheet.
(Design has been roughly adapted from Summit Hackathon Figma document)
> Link to base USWDS component documentation

- CHANGELOG.md
- src/scss/components/_typography.scss
**Why**: It's assumed _(confirmation needed)_ that the intention of these selectors was to match headings within `.usa-prose` following any other content in that prose block. Instead, due to the behavior of `&` in expanding the full selector ancestry, the generated output was along the lines of...
```
*+.usa-prose>h2,*+.usa-prose>h3 {
margin-top: 1.7em
}
```
This can be interpreted as "a heading within a prose block, where the prose block itself is preceded by any other content".
This is expected to have a visual impact on headings in prose content. Example, from the ["Typography" page](https://design.login.gov/typography/):
Before|After
---|---
Given that this styling has existed for quite a while, it may be worth reevaluating if the margins are still desirable.
> Fix prose sibling heading margin selectors

- CHANGELOG.md
- package.json
Regression introduced in: #165
**Why**: So that projects importing subpaths from identity-style-guide don't fail if they respect native ES module `exports` definitions.
See: https://nodejs.org/api/packages.html#packages_package_entry_points
Specifically, the problem being fixed is one explicitly described in the above documentation:
>**Warning**: Introducing the `"exports"` field prevents consumers of a package from using any entry points that are not defined, including the `package.json` (e.g. `require('your-package/package.json')`. **This will likely be a breaking change.**
The intent with these changes is to allow for easier upgrades in projects which may be importing one of these paths ([example](https://github.com/18F/identity-site/blob/1bff268dbffe6b50affc513ba9c9097d942ba5bb/assets/ …
> Fix native ES module subpath resolution

- CHANGELOG.md
- src/scss/components/_buttons.scss
This pull request seeks to resolve an issue where focused buttons appear with two focus rings. The button styles included in the design system intend to unset the inherited focus styles from USWDS, but are not of high enough specificity to override the styles.
Reference: https://github.com/uswds/uswds/blob/1f9bb1cc/src/stylesheets/global/_focus.scss#L1-L11
Before|After
---|---
> LG-4226: Fix double focus ring

- README.md
**Why**:
- Changelog should be edited to replace "Unreleased" with the release version.
- Main branch is protected, so you cannot commit the version bump directly. Improve text to include steps for creating a branch, opening a pull request, and merging before creating a new release.
- Dry-run testing is all well and good, but there wasn't any guidance around what exactly one should be looking for in considering whether "everything looks alright". Add a couple tips on what to look for.
> Improve README guidance for release process

- CHANGELOG.md
- src/scss/uswds-theme/_color.scss
For context, see: https://github.com/18F/identity-style-guide/pull/191/files#r582962658
Active color is left unchanged as `primary-darker`.
> Change link hover color from "primary-darker" to "primary-dark"

- CHANGELOG.md
- package.json
The package uses `sideEffects` along with ES Module `exports` to allow consuming projects to optimize the amount of code generated when using individual components from the package, via dead-code elimination / ["tree shaking"](https://webpack.js.org/guides/tree-shaking/). `sideEffects` instructs the bundler that there are no side-effects in importing the code, and that it's safe to discard code except for direct references to exported members.
However, this project also distributes an "auto" version, which is intended to automatically handle initialization for all components simply by being loaded:
```js
import 'identity-style-guide/auto';
```
This requires side effects, and therefore must be made an exception by passing paths as an array to `sideEffects` ([see …
> Fix sideEffects package configuration for "auto" entrypoints

- CHANGELOG.md
- docs/_components/buttons.md
- docs/_includes/helpers/unstyled-button.html
- src/scss/components/_buttons.scss
The unstyled button variant had previously existed in that it was inherited from USWDS, though it was not documented, and did not always display correctly, particularly in hover, active, and focus states. These changes improve this support, and adds documentation for the unstyled option.
**Live Preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-lg-4226-document-variants/components/buttons/
> LG-4226: Improve support for unstyled button

- CHANGELOG.md
- docs/_components/buttons.md
- src/scss/components/_buttons.scss
Adds two new button variants:
1. Minimum width occupies full width on mobile, and a minimum width on wider viewports
2. Full width always occupies full width
**Questions:** (cc @anniehirshman-gsa)
1. The Figma includes text "All buttons default to full width for mobile viewports". Should this behavior apply to the unmodified `usa-button` ("flexible") button, or only minimum-width and full-size buttons?
2. The Figma mentions using `btn-wide` as the class for a minimum width button. As implemented here, I chose to follow the BEM convention as `usa-button--wide`. Is that okay?
3. What specific breakpoint should mobile behavior stop taking effect ([see USWDS "Utility breakpoints"](https://designsystem.digital.gov/documentation/settings/#utilities-settings))? As implemented here is `tablet`. …
> LG-4226: Add wide button variants

- CHANGELOG.md
- docs/_components/buttons.md
- docs/_includes/helpers/unstyled-button.html
- src/scss/components/_buttons.scss
This pull request...
- Updates Buttons page to include Big button examples.
- Small adjustments to Big button sizing per Figma design (padding, font size, line height).
- Renames "Secondary" button to "Outline" button
- Note: In code, "Secondary" still exists, and is effectively aliased as the outline button. This is how it was implemented previously, and otherwise we'd inherit USWDS secondary button styling, which may not be desirable or at least not predictable in its usage.
Note: Between this and #191, whichever is merged first, the other should include and verify the behavior of the unstyled, big button. I tested this locally and it appeared to work reasonably well out of the box.
**Live Preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/pr …
> LG-4226: Document current button offerings ("big", "outline")

- CHANGELOG.md
- docs/_components/buttons.md
- src/scss/components/_buttons.scss
**Why**: As a consumer of the login.gov Design System, I expect to be able to override the default full-width button appearance on mobile to allow for flexible-width buttons, so that I can create interfaces where the button is shown adjacent to other text or controls.
Currently, all buttons are shown as full-width at mobile viewports. There are a few instances in the IDP of buttons appearing as flexible width at mobile viewport sizes, with text or interactive content shown next to the button ([example](https://user-images.githubusercontent.com/1779930/109558515-88e88900-7aa7-11eb-9148-b5c0c6d7b62c.png)). These are not the majority, so an override option is included to let the developer choose to force the width to shrink as flexible, while retaining the current default behavior.
In …
> LG-4226: Add explicit flexible width button modifier

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/components/_buttons.scss
Regression of #193 (69a13a0342ae871cac8383e138d4b603b45f4d04).
**Why**: For consistency with other buttons and to align to expected design specs, there should only be a single outline on any focussed button.
Before|After
---|---
**Live Preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-fix-unstyled-focus/components/buttons/
**Implementation Notes:**
Refactoring in #193 rearranged styles such that [our re-application of the unstyled mixin](https://github.com/18F/identity-style-guide/blob/8a6b48308f27cf7f6b75df54cdc50981f3708722/src/scss/components/_buttons.scss#L15-L19) would reintroduce focus styles through [the mixin's use of link styles](https://github.com/uswds/uswds/blob/0c95fd94ecdb646f360592aa01c55dc386ce407b/src/st …
> LG-4226: Fix double focus ring on unstyled buttons

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/components/_buttons.scss
Related Slack conversation: https://gsa-tts.slack.com/archives/CNCGEHG1G/p1616421634001700
**Why**: The use of an unstyled button is intended to take the visual appearance of a link. The proposed changes resolve some discrepancies that currently exist:
- Avoid customizing the underline offset
- Reset font smoothing using `inherit` (see https://github.com/uswds/uswds/pull/4115 for detail)
**Live Preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-unstyled-buttons-links/components/buttons/
Before|After
---|---
This was originally observed in the IdP, where an equivalent link and unstyled button did not appear the same. See examples below which show a real link on the left vs. an unstyled button on the right. …
> Buttons: Improve unstyled button styles to visually match link appearance

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/components/_buttons.scss
**Why**: These were applied to modifier states for unstyled buttons in #201, but should have also been applied to the base styles, to override USWDS unstyled button styles.
> Apply inherited font smoothing to base unstyled button styles

- CHANGELOG.md
- src/scss/components/_buttons.scss
- src/scss/uswds-theme/_components.scss
**Why**: Per Figma design reference, the outline button should only have a border width of 1px, not 2px. The "Big" outline button should still have a 2px border.
**Live Preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-outline-button-border-width/components/buttons/
_Design System:_
Before|After
---|---
_IdP:_
Before|After
---|---
**Implementation Notes:**
USWDS allows customization of the stroke width of an outline button, but does not allow for different values between default and big versions of the button. Implementing this requires duplicating the base styles with a custom "big" stroke width, computed here as double the value of the new default stroke width of `1px`.
> Reduce border width on default outline button

- CHANGELOG.md
- docs/_components/search.md
- docs/_components/side-navigation.md
- src/scss/components/_sidenav.scss
Why:
- To document customizations made between LGDS and USWDS
> Add custom components to LGDS

- Makefile
- README.md
- package.json
**Why**: Federalist will install all dependencies for us. Previously we needed to re-run the NPM install in order to install development dependencies in addition to production dependencies. As of the Federalist release this past Friday, it will install all dependencies, so this will no longer be necessary.
**Note:** All Federalist builds will fail until this pull request is merged.
Related discussion: https://gsa-tts.slack.com/archives/C1NUUGTT5/p1617287819021500
> Fix build setup to be compatible with latest Federalist release

- CHANGELOG.md
- src/scss/components/_inputs.scss
See discussion: https://github.com/18F/identity-dashboard/pull/420#discussion_r615840215
**Why**: Search input corners are intended to be squared in USWDS, but it is being overridden unintentionally by our `.usa-input` border radius customizations.
- Border
- Original: https://github.com/uswds/uswds/blob/0f1f4d0/src/stylesheets/components/_search.scss#L83
- Customized: https://github.com/18F/identity-style-guide/blob/ba2b1f7/src/scss/components/_inputs.scss#L7
- Border radius
- Original: https://github.com/uswds/uswds/blob/0f1f4d0/src/stylesheets/components/_search.scss#L82-L84
- Customized: https://github.com/18F/identity-style-guide/blob/ba2b1f7/src/scss/components/_inputs.scss#L10
**Live preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identit …
> Fix search input square corners

- CHANGELOG.md
- gulpfile.js
- package-lock.json
- package.json
- src/scss/styles.scss
- src/scss/uswds
**Why**: To match USWDS intended load order of stylesheets, to allow utility classes to take precedence over component styles, and to facilitate a potential future use of [USWDS 2.11.0 package subsetting](https://designsystem.digital.gov/about/releases/#v2.10.0%20Beta%200-intermediate-package-subsetting).
USWDS [loads utility stylesheets after components](https://github.com/uswds/uswds/blob/develop/src/stylesheets/uswds.scss), allowing for those utility classes to apply usually as expected as an override to the component style selectors of equal specificity, as an alternative to resorting to [`$utilities-use-important`](https://github.com/uswds/uswds/blob/1908d1391bc59410624ca1934cc70b7404e8f443/src/stylesheets/theme/_uswds-theme-utilities.scss#L20).
Previously, we imported all USWDS …
> Load utility classes after components

- CHANGELOG.md
- docs/usage.md
- src/scss/packages/_components.scss
- src/scss/packages/_global.scss
- src/scss/packages/_required.scss
- src/scss/packages/_utilities-required.scss
- src/scss/packages/_utilities.scss
- src/scss/styles.scss
**Why**: To limit or control the loading of styles.
Use-cases:
1. Avoid specificity conflicts between utility classes and a consuming project's custom components
2. Load only required mixins and functions to support CSS code splitting
This also mirrors USWDS packages, with two main differences:
- Simplifies naming of `uswds-components` and `uswds-utilities` to just `components` and `utilities`
- Extracts `utilities-required` from `utilities` to allow non-rendering import of utility mixins.
See:
- https://designsystem.digital.gov/components/packages/
- https://github.com/uswds/uswds/blob/develop/src/stylesheets/uswds.scss
Next steps:
Per the above use-cases, this is useful for `identity-idp` and the following diff would help toward resolving existing specificity conflicts and simplify code …
> Add package entrypoints for granular stylesheet loading

- CHANGELOG.md
- src/scss/components/_buttons.scss
Related: https://github.com/18F/identity-idp/pull/4825#discussion_r600735686
**Why**:
- Account for missing `usa-button--unstyled:hover` and `usa-button--unstyled:active`
- Single point to remove in the future, as noted in the preceding comment
> Consolidate unstyled button font smoothing styles

- CHANGELOG.md
- package-lock.json
- package.json
Changelog:
>## 5.1.0
>
>### New Features
>
>- Add support for SASS package entrypoints to limit or control loading of styles, [similar to USWDS components](https://designsystem.digital.gov/components/packages/). Available packages are `packages/required`, `packages/global`, `packages/components`, and `packages/utilities`.
>- The [Side Navigation component](https://design.login.gov/components/side-navigation/) is now documented and includes updated and improved styling. While this should not require any markup changes, you should validate that the updated styling does not conflict with any product-specific styles for side navigation.
>
>### Bug Fixes
>
>- Reduce the border width of the normal outline button to the intended width of `1px` (previously `2px`). The big variant of the outline …
> Prepare 5.1.0 release

- test/dist/scss.test.js
**Why**: So that the build doesn't fail by exceeding the default timeout of 5 seconds, where allowing the compilation to complete would otherwise succeed.
We should revisit the fact that this test is as slow as it is in the first place, possibly:
- Replacing `gulp-sass` compiler (using `node-sass` under the hood) with Dart-based SASS ([benchmarks](https://github.com/sass/dart-sass/blob/master/perf.md), e.g. currently-experimental [`sass-embedded`](https://www.npmjs.com/package/sass-embedded))
- Combining tests
- Limiting what we need to import to verify the expected behavior (vs. entire USWDS)
> Bump Jest timeout for SCSS compilation tests

- src/img/close-primary.svg
- src/img/close.svg
- src/scss/components/_navbar.scss
- src/scss/components/_sidenav.scss
**Why**: The USWDS upgrade in #219 changed default padding for most navigation menus. This was corrected in the side navigation, but mobile primary navigation still appeared more condensed than previously. Additionally, default scaling for the navigation close button was changed in USWDS to be much larger due to a change to use the new icon set, causing the icon to appear very large. The design system was not using our custom version of the icon anyways. This has been corrected.
Before|After
---|---
Open questions:
- _Is this what we want the menu to look like?_ I couldn't find a canonical reference for what the mobile menu should look like. The adjustments here are a best compromise of restoring previous expectations. This could be a good opportunity to make updates if we wanted.
- _Do …
> Fix mobile primary navigation styles

- CHANGELOG.md
- _config.yml
- docs/_components/code-formatting.md
- docs/_components/search.md
- docs/_includes/helpers/base-component.html
- docs/_includes/navbar.html
- docs/brand.md
- docs/color.md
- docs/content.md
- docs/images.md
- docs/index.md
- docs/typography.md
- package.json
- src/img/favicons/manifest.json
⚠️ This pull request is downstream from #228 and should not be merged in until that PR is merged.
The Login.gov program is removing the branding guidance for using a lowercase "l" when using "Login.gov" in the middle of a sentence. Login.gov is a proper noun and should be used as such to avoid confusion and leverage plain language throughout our branding.
:hat-tip: to @Danielle-Lee
> Update capitalization guidance in content guide

- docs/content.md
This pull request adds in specific guidance on updating Login.gov to always be capitalized, see screenshot.
Ref #231
> Add specific guidance for new capitalization of Login.gov.

- src/scss/uswds-theme/_color.scss
**Why**: The upstream fix was merged and released in USWDS 2.10.0.
> Revert temporary workaround for upstream fix

- test/color.test.js
**Why**: The URL changed from `/color/` to `/utilities/color/` in #233. This updates the integration test accordingly, so that it doesn't fail.
> Fix integration tests for Color page

- CHANGELOG.md
- package-lock.json
- package.json
Formality to publish the current `main` branch to NPM as 6.0.0, needed as part of LG-4502 to use the new bordered checkbox input.
Changelog:
>## 6.0.0
>
>### Breaking Changes
>
>- USWDS is upgraded to the latest version, from v2.9.0 to v2.11.2.
>   - The bordered and large styles of checkboxes and radio buttons have updated guidance to improve compatibility with the [USWDS tile style](https://designsystem.digital.gov/components/radio-buttons/). The classes `usa-radio-bordered`, `usa-radio-large`, `usa-checkbox-bordered`, and `usa-checkbox-large` have been removed. Instead, add `usa-radio__input--bordered`, `usa-radio__input--tile`, `usa-checkbox__input-bordered`, `usa-checkbox__input--tile` respectively as modifiers to the element with the class `usa-radio__input` or …
> Prepare 6.0.0 release

- CHANGELOG.md
- docs/_components/form-fields.md
- src/scss/components/_inputs.scss
Related: https://github.com/uswds/uswds/pull/4286
Context: https://github.com/18F/identity-idp/pull/5279#discussion_r686146591
This pull request seeks to maintain the existing visual appearance of the Checkbox and Radio Button components, while improving developer ergonomics regarding HTML whitespace sensitivity.
See additional details at https://github.com/uswds/uswds/pull/4286 .
The expectation is that there should be no user-facing visual effect of these changes, hopefully demonstrated by a passing visual regression test.
This does not incorporate [other design revisions proposed for the checkbox and radio component](https://gsa-tts.slack.com/archives/C01JVKYE4KD/p1628869289001500), which will be implemented separately.
> Checkbox / Radio Button: Improve HTML whitespace sensitivity

- CHANGELOG.md
- src/scss/components/_links.scss
- src/scss/packages/_components.scss
Backported from https://github.com/18F/identity-idp/pull/5300 (see [design feedback](https://github.com/18F/identity-idp/pull/5300#pullrequestreview-734356031))
This adds a small additional buffer between the external link icon and surrounding text, previous 2px left margin and 0px right margin, now 4px left margin and 2px right margin.
Before|After
---|---
Live preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-external-link-margin/components/accordions/
Visual regression tests are expected to fail.
> Increase external link margin styling

- Makefile
**Why**: To avoid false positives where `npm install` may touch `package-lock.json` without actually making content changes.
See: https://github.com/npm/cli/issues/3225
`git diff-index` doesn't always accurately reflect the content of the file itself:
>As with other commands of this type, git diff-index does not actually look at the contents of the file at all. So maybe kernel/sched.c hasn’t actually changed, and it’s just that you touched it. In either case, it’s a note that you need to git update-index it to make the index be in sync.
Via: https://git-scm.com/docs/git-diff-index
Also aligns with similar implementations in other Login.gov repositories, e.g.: https://github.com/18F/identity-idp/blob/278823d3622dff0f42a50a9ff6a23f0a036e4602/Makefile#L58-L59
> Improve package-lock.json validation

- CHANGELOG.md
- README.md
- src/scss/uswds-theme/_color.scss
- src/scss/uswds-theme/_components.scss
- src/scss/uswds-theme/_general.scss
- src/scss/uswds-theme/_typography.scss
- src/scss/uswds-theme/_utilities.scss
**Why**: To allow per-project customization, which previously required cumbersome workarounds.
Documentation: https://sass-lang.com/documentation/variables#default-values
Real-world examples: https://github.com/18F/identity-site/search?l=SCSS&q=todo
> Define all variables as default values

- CHANGELOG.md
- src/scss/uswds-theme/_utilities.scss
**Why**: These were kept in #236 as they differed from USWDS defaults, but they _were_ identical to the default as of the original file creation. USWDS later [changed the default](https://github.com/uswds/uswds/commit/16806bde246f61207cd64bfbf2e21c5a3a8b998b), and since we had no explicit reason to disable responsive styles, we should inherit the default instead.
> Remove width non-responsive override

- CHANGELOG.md
- src/scss/components/_navbar.scss
**Why**: Per Figma design system "Layouts and templates". This is already applied to the brochure site via [style override](https://github.com/18F/identity-site/blob/25d5b444c3b8852b5000721837e84aef75a92512/_sass/components/_nav.scss#L191), and reflected in upcoming Partnerships site design.
Before|After
---|---
> Remove uppercase transform from navbar styles

- README.md
Previously: #170
**Why**: So that the documentation is accurate. Earlier iterations had named the helper method login_design_asset_path . Rename design_system_asset_path to improve future compatibility with naming and to be more clearly associated with design system.
> Fix typo in Rails asset helper documentation

- docs/_includes/helpers/base-component.html
- docs/_plugins/content_typography.rb
- docs/_utilities/color.md
- docs/index.md
Related: https://github.com/18F/identity-handbook/pull/163
**Why**: Because a design system's documentation should ideally leverage said design system's own link styles.
Live preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-docs-links/
Before|After
---|---
> Use design system link styles in documentation

- dependabot.yml
**Why**: To reduce confusion and maintenance overhead incurred by version drift, to simplify the sync process, and to take advantage of the latest features and bug fixes as quickly as they're made available.
Reference: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates
> Configure auto-updates for USWDS

- CHANGELOG.md
- docs/_components/form-fields.md
- src/scss/components/_inputs.scss
- src/scss/uswds-theme/_components.scss
- test/dist/scss.test.js
**Why**: As an end-user, if I try to submit a form with invalid form values, I want to see consistent and accessible messaging that tells me what I need to complete before I can submit the form successfully.
References:
- LG-4235
- https://gsa-tts.slack.com/archives/C01JVKYE4KD/p1632934852000500
Before|After
---|---
Live preview URL: TBD
> Update form validation error message styling

- CHANGELOG.md
- src/scss/components/_buttons.scss
Context: https://github.com/18F/identity-idp/pull/5394#issuecomment-918153858
**Why**: To maintain a consistent visual style between links and unstyled buttons.
Before|After
---|---
Live preview URL: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-unstyled-button-focus-outline/components/buttons/#unstyled
> Use default focus outline for unstyled buttons

- CHANGELOG.md
- package-lock.json
- package.json
Changelog:
>### New Features
>
>- All theme variables are now set as [default values](https://sass-lang.com/documentation/variables#default-values), allowing you to override them for per-project requirements. ([#247](https://github.com/18F/>identity-style-guide/pull/247))
>   - Note: Since the design system is meant to be an opinionated set of smart defaults, it's recommended to use restraint with variable customization, or at least consider when it may be more appropriate to adjust a setting from the design system itself in order to maintain consistency across projects.
>- Responsive variants of width utility classes are now enabled. ([#248](https://github.com/18F/identity-style-guide/pull/248))
>### Improvements
>- Navbar link text is no longer uppercase. …
> Prepare 6.2.0 release

- CONTRIBUTING.md
**Why**: To better communicate the approach to extending USWDS.
> Add "Coding Standards" section to contributing guide

- gulpfile.js
**Why**: Because it's much faster.
Reference: https://github.com/dlmanning/gulp-sass#usage
_Before:_
```
[09:28:52] Finished 'build-sass' after 44 s
```
_After:_
```
[09:43:04] Finished 'build-sass' after 16 s
```
> Build SASS synchronously

- docs/_components/buttons.md
**Why**: So that all of the button previews appear on the same line, and for consistency with how this is already handled for larger button variants.
By default, content in a Markdown file is rendered in paragraph elements within a `usa-prose` block which constrains the width of the content. This is a good thing for text content, since it helps limit line length. However, it doesn't make sense for component previews.
Before|After
---|---
Review with whitespace hidden: https://github.com/18F/identity-style-guide/pull/273/files?w=1
> Fix line wrapping for Buttons documentation

- _config.yml
- docs/_plugins/site_url.rb
- package-lock.json
- package.json
- scripts/pa11y.sh
- test/screenshot.test.js
Inspired by: https://github.com/18F/handbook/pull/2928 ([relevant Slack discussion](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1637088742004300), h/t @mgwalker )
This pull request attempts to improve the Jekyll `url` configuration to accommodate different combinations of...
- Build environments
- Local development
- Federalist preview sites
- Federalist live site
- Jekyll plugins
- `jekyll-redirect-from`
- `jekyll-sitemap`
The current configuration has a few issues:
- It wrongly assigns Federalist URLs as values in the [live site sitemap.xml](https://design.login.gov/sitemap.xml)
- Sitemap URLs for preview sites are invalid ([example](https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-backport-more-search/sitemap.xml))
- …
> Fix Jekyll site URL assignment

- CHANGELOG.md
- src/scss/components/_inputs.scss
**Why**: The [error input style selector in USWDS](https://github.com/uswds/uswds/blob/eb84a497042aa85d79e8b5d2225a874c210bdb33/src/stylesheets/elements/form-controls/_text-input.scss#L11-L13) does not qualify as one of `.usa-input`, `.usa-textarea`, or `.usa-select`. In many cases, this makes little difference since the modifier would be applied to an element with one of those classes. However, this is not strictly required, and causes some [challenge in the IdP with SimpleForm compatibility](https://github.com/18F/identity-idp/pull/5626), where design system classes are not yet being applied (pending LG-3877). Furthermore, per updated guidance in #271, selectors with overriding styles should seek to precisely match the USWDS selector it is overriding.
Future work should seek to bring …
> Match usa-input-error selector to USWDS

- CHANGELOG.md
- docs/_components/process-list.md
- docs/_includes/helpers/base-component.html
- scripts/pa11y.sh
- src/scss/components/_process-list.scss
- src/scss/packages/_components.scss
- src/scss/uswds-theme/_components.scss
Base styling is smaller and excludes the connector otherwise shown with the base [USWDS Process List component](https://designsystem.digital.gov/components/process-list/).
A "connected" (`.usa-process-list--connected`) variant restores the connector.
A "big" (`.usa-process-list--big`) variant increases the size of the numbered circle.
They can also be used in combination with the other.
Live preview URL: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-process-list/components/process-list/
> LG-4791: Add Process List component styles

- CHANGELOG.md
- docs/_components/search.md
- src/scss/components/_search.scss
- src/scss/packages/_components.scss
- Full button text "Search" is always shown, regardless of viewport size
- Reduce padding for default search button from 2 units (1rem) to 1.5 units (0.75rem)
- Reduce font size for default search button from xs (1rem) to 2xs (0.87rem)
Live preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-backport-more-search/components/search/
> Backport additional search styles from brochure site

- CHANGELOG.md
- src/scss/components/_inputs.scss
- src/scss/uswds-theme/_typography.scss
**Why**: So that multi-line checkbox or radio fields do not appear tighter relative to surrounding body copy.
Note: This also changes the default line-height, configured to match secure.login.gov (changes from 1.6 default to 1.5).
Before|After
---|---
> Set checkbox/radio label line-height to match body

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/components/_process-list.scss
**Why**: So that headings do not appear excessively tight when spanning multiple lines.
This uses the theme-configured heading line-height variable (`$theme-heading-line-height`), replacing the hard-coded value of `2` from USWDS, which would previously result in a line-height of 1.1.
Live preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-process-list-line-height/components/process-list/
These are in context of the implementation of https://github.com/18F/identity-idp/pull/5863.
Before|After
---|---
> Improve vertical spacing in heading of Process List item spanning multiple lines

- CHANGELOG.md
- src/scss/components/_process-list.scss
**Why**: The Process List component includes some top and bottom padding inherited from USWDS, making it difficult to position in content, where surrounding content's own margins may cause excess space. Most components don't (and shouldn't) include any inherent vertical spacing, allowing the developer to decide to apply margins as appropriate, or rely on margins from surrounding content. Margins also have the added benefit of allowing for [margin collapse](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) behavior, to allow the component to be more easily reused in content without awareness of the specific context of its surrounding content.
Related discussion: https://github.com/18F/identity-idp/pull/5863#issuecomment-1028374791
Live preview URL: …
> Remove vertical padding from Process List component

- CHANGELOG.md
- src/scss/uswds-theme/_typography.scss
Related Slack discussion: https://gsa-tts.slack.com/archives/CNCGEHG1G/p1644337817896069?thread_ts=1644246272.507329&cid=CNCGEHG1G
**Why**: Previously with Source Sans, a body font size of "xs" would result in an effective font size of 1rem, due to scaling resulting from its [smaller cap height](https://github.com/uswds/uswds/blob/61a0d99f0e6b36c3758948ba6ac46140abc5e585/src/stylesheets/core/_system-tokens.scss#L282) relative to the [base cap height](https://github.com/uswds/uswds/blob/61a0d99f0e6b36c3758948ba6ac46140abc5e585/src/stylesheets/core/_system-tokens.scss#L416). In Public Sans, "xs" results in an effective font size of 0.94rem. To restore the desired 1rem body font size, we should drop this override and inherit the USWDS default "sm".
Live preview URL: …
> Change body font size to USWDS default "sm"

- CHANGELOG.md
- src/scss/components/_inputs.scss
In order to have the correct sizing of svg icons (24px) for the illustrated ratio inputs, we need to update the width from 1 to 1.5 rem.
> update radio image width

- CHANGELOG.md
- src/scss/components/_general.scss
**Why**: Because it's already set through USWDS.
See: https://github.com/uswds/uswds/blob/86636ea/src/stylesheets/settings/_settings-color.scss#L136
Before|After
---|---
> Remove redundant body background color

- CHANGELOG.md
- src/scss/components/_buttons.scss
- src/scss/components/_inputs.scss
- src/scss/functions/_focus.scss
- src/scss/packages/_required.scss
**Why**: To reduce the amount of generated styles for controlling focus appearance of fields, and to avoid error-prone reimplementation of focus styles by leveraging default styles and only overriding as needed.
Ideally there should be no visual changes associated with these revisions, which should be covered decently well with visual regression tests, as both buttons and radio/checkbox fields are documented with a full set of states.
> Reconcile focus styles with USWDS

- CHANGELOG.md
- docs/_layouts/main.html
- src/scss/components/_typography.scss
**Why**: So that the design system artifact includes only styles which apply across projects.
In practice, this seems to only have the minor effect of altering the margin between documentation page heading and the subsequent paragraph (0.4rem to 0.5rem, or 0.5rem to 1rem), which does not seem worthwhile to maintain.
It's expected that visual regression tests would fail, and demonstrate the visual difference.
> Remove documentation styles from stylesheets

- CHANGELOG.md
- package-lock.json
- package.json
Following release process: https://github.com/18F/identity-style-guide#releases
Changelog: 
>## 6.4.0
>
>### Deprecation Notice
>
>- The `alerts/success-badge.svg` image will be removed in a future major version. Use `alerts/success.svg` instead. ([#306](https://github.com/18F/identity-style-guide/pull/306))
>
>### Improvements
>
>- Improve appearance of illustrated tile checkboxes and radio buttons. ([#309](https://github.com/18F/identity-style-guide/pull/309))
>
>### Bug Fixes
>
>- Use correct "Success" green color for `alerts/unphishable.svg` icon. ([#306](https://github.com/18F/identity-style-guide/pull/306))
>
>### Optimization
>- Remove documentation-specific images from published package. ([#300](https://github.com/18F/identity-style-guide/pull/300))
>- Remove duplicate styles. …
> Prepare 6.4.0 release

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/components/_search.scss
Fixes regression of #259
**Why**: Because the submit button should have a visible text label.
Slack context: https://gsa-tts.slack.com/archives/C01710KMYUB/p1649431326074669
Live preview URL: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-fix-hidden-search-text/components/search/
Before|After
---|---
> Fix hidden search submit button text on small viewport

- CHANGELOG.md
- package-lock.json
- package.json
Following release process: https://github.com/18F/identity-style-guide#releases
Changelog: 
> ## 6.4.2
> 
> ### Dependencies
> 
> - Update USWDS from v2.13.2 to 2.13.3. ([#312](https://github.com/18F/identity-style-guide/pull/312))
> 
> ### Improvements
> 
> - Add styles and markdown content for selected and disabled radios and checkboxes. ([#313](https://github.com/18F/identity-style-guide/pull/313))
> Prepare Release 6.4.2

- CHANGELOG.md
- src/scss/components/_accordions.scss
- src/scss/components/_banner.scss
**Why**: To improve readability when the accordion heading spans multiple lines of text.
**Live preview:** https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.app.cloud.gov/preview/18f/identity-style-guide/aduth-lg-6485-accordion-line-height/components/accordions/
Before|After
---|---
> LG-6485: Update line height value for accordion component

- CHANGELOG.md
- package-lock.json
- package.json
Following release process: https://github.com/18F/identity-style-guide#releases
Changelog: 
>## 6.5.0
>
>### Improvements
>
>- Increase line-height for accordion heading content to improve readability. ([#316](https://github.com/18F/identity-style-guide/pull/316))
> Prepare 6.5.0 release

- docs/security-experience-principles.md
**Proposal:** To reflect the latest content from the upcoming Partners site. So that both sites are aligned.
**Background context:** The content changes were prompted by accessibility testing with the Partners site, which Chanan and Danielle have reviewed.
> Update Security experience link content

- Makefile
- README.md
- docs/_plugins/site_url.rb
- docs/_plugins/warn_without_make.rb
- package.json
**Why**: [Federalist is becoming Cloud.gov Pages](https://cloud.gov/pages/federalist-migration/), and as such we'll need to update configurations accordingly.
The webhook settings have already been updated, so these changes are updating documentation and code references to Federalist.
> Migrate Federalist to Cloud.gov Pages

- CHANGELOG.md
- docs/_components/form-fields.md
- src/scss/elements/form-controls/_all.scss
- src/scss/elements/form-controls/_text-input.scss
Adds new "Big" variants of Text Input and Textarea components to reflect Figma LGDS reference, and to support migration toward design system inputs in the IdP.
Live preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.sites.pages.cloud.gov/preview/18f/identity-style-guide/aduth-big-text-inputs/components/form-fields/
> Add "Big" variant of Text Input, Textarea

- CHANGELOG.md
- docs/_components/form-fields.md
- package-lock.json
- package.json
- src/scss/elements/form-controls/_all.scss
- src/scss/elements/form-controls/_dropdown.scss
- src/scss/elements/form-controls/_text-input.scss
As part of IdP migration to design system fields, missed in #326 / v6.6.0.
Live preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.sites.pages.cloud.gov/preview/18f/identity-style-guide/aduth-big-select/components/form-fields/#dropdowns
Related discussion: https://docs.google.com/document/d/1CXbI0ji8SUMVqXccoDGZgEkJ5gsoPUpNZUN8MRB0oTs/edit?disco=AAAAl-0lStw
> Add Big variant of Dropdown component

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
* Improve discoverability for people searching for the Login.gov Design System
* Scope package to organization to adhere to best practices
Follow-up:
* Rename repository in GitHub repository settings.
* Consider resetting version count to 1.0.0 in `package.json`
> Rename project to identity-design-system, scope package to 18F

- CHANGELOG.md
- docs/_components/cards.md
- docs/_includes/helpers/unstyled-button.html
- docs/_layouts/main.html
- src/scss/components/_buttons.scss
- src/scss/components/_search.scss
- src/scss/components/_typography.scss
Fixes issue where documentation pages with sidebar appear incorrectly stacked. Consistent with changes proposed in #298 (specifically 24ed5612793536cd50d1c2e3090ff47cc8cd2b2d), standardize on the "tablet" breakpoint.
This breakage of the documentation site wasn't caught by visual regression specs since the screen size for visual regression specs was set to a size which wouldn't have been affected by this change.
> Standardize on "tablet" layout breakpoint

- CHANGELOG.md
- docs/_components/form-fields.md
- src/scss/components/_inputs.scss
This removes the `.usa-form-hint` class, which was deprecated in USWDS v2 ([documentation](https://designsystem.digital.gov/documentation/migration-v2/#inputs)). See https://github.com/18F/identity-dashboard/pull/634 for removal of the only downstream usage I could find.
The class was also used internally in the Memorable Date component guidance. I took the opportunity to update the markup to align to the new select-based dropdown. This documentation may be short-lived anyways, what with https://design.design.gov slated for deprecation.
Before|After
---|---
> Remove deprecated hint class, update Memorable Date guidance

- CONTRIBUTING.md
- README.md
Why? To tailor the document toward an audience which is primarily interested in using the design system on a Login.gov project, not contributing to the design system itself. This also favors documentation which describes a Sass compilation process, and new requirements of USWDS v3. It also recommends the [identity-build-sass](https://www.npmjs.com/package/@18f/identity-build-sass) NPM package as an easier way to get started.
The existing documentation relevant for contributing to the project itself still exists, but has been relocated to CONTRIBUTING.md.
For review, it's probably easiest to just view the new document, since it's essentially recreated from scratch:
https://github.com/18F/identity-style-guide/blob/aduth-update-readme-usage/README.md
> Update README.md for USWDS 3 usage guidance

- test/screenshot.test.js
Fixes an issue where visual regression tests are failing due to an issue introduced with the upgrade of dependencies, including Puppeteer. See https://github.com/18F/identity-style-guide/pull/339#issuecomment-1513335517 for more context, where the issue continued into subsequent pull requests (#342, for example).
This was just a guess at a solution to try to wait until the page load was more "stable" before taking the screenshot, but it appears to be working on first pass.
Related documentation: https://pptr.dev/api/puppeteer.page.goto/#remarks
> Fix screenshot regression tests

- Makefile
- gulpfile.js
- package-lock.json
- package.json
Why? So that the package isn't exceedingly large or include files that are not necessary.
Previously, we would copy Sass files from `src/assets/scss` to `dist/assets/scss`, but with the updated usage recommending to use the `packages/` entrypoint (see README.md), the `dist/assets/scss` directory is not necessary.
Additionally, when running `npm publish --dry-run`, I was seeing that there was some `node_modules` files being included, which turns out to be an upstream issue for USWDS (see https://github.com/uswds/uswds/pull/5245). I've excluded them here as well.
> Limit size of published Sass content

- src/scss/packages/_usa-alert.scss
Why?
- USWDS upgrade regressed two intended styles:
- Overriding horizontal padding
- Setting border radius on the alert
Before|After
---|---
> Fix alert padding and border radius (USWDS 3 upgrade regression)

- CHANGELOG.md
- docs/_components/tags.md
- src/scss/packages/_usa-tag.scss
Implements Tag styles consistent with the Figma specifications.
IdP styles: https://github.com/18F/identity-idp/blob/main/app/assets/stylesheets/components/_tag.scss
Preview: https://federalist-2f194a10-945e-4413-be01-46ca6dae5358.sites.pages.cloud.gov/preview/18f/identity-style-guide/aduth-lgds-tag/components/tags/
> Backport Tags styles from IdP

- docs/_components/accordions.md
- docs/_components/alerts.md
- docs/_components/buttons.md
- docs/_components/form-fields.md
- docs/_components/process-list.md
- docs/_components/side-navigation.md
- docs/_includes/helpers/base-component.html
Since the folder structure and file naming conventions changed in the USWDS v3 upgrade, these were previously 404-ing in many cases.
**Testing Instructions:**
Confirm in the preview "Components" pages that "View USWDS component for guidance" and "View Login.gov SCSS on GitHub" links don't 404.
> Fix links for base component information

- .circleci/config.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- _config.yml
- docs/_includes/helpers/base-component.html
- docs/index.md
- package.json
This updates internal code references to the GitHub repository.
Next steps:
- Rename repository in Settings
- Replace site in Cloud.gov Pages
> Prepare repository rename "identity-style-guide"

- CHANGELOG.md
- package-lock.json
- package.json
>## 7.0.0
>
>### Breaking Changes
>
>- NPM package renamed from `identity-style-guide` to `@18f/identity-design-system`. ([#331](https://github.com/18F/identity-design-system/pull/331))
>- Update USWDS from 2.13.3 to 3.4.1. ([#321](https://github.com/18F/identity-style-guide/pull/321))
>  - Polyfills have been removed, consistent with current Login.gov browser support
>  - The following JavaScript named exports have been renamed or removed:
>    - `navigation` is renamed to `header`
>    - `validator` is renamed to `validation`
>  - Refer to README.md for updated usage instructions, as well as the [U.S. Web Design System migration guide](https://designsystem.digital.gov/documentation/migration/).
>- Sass artifacts now require Dart Sass. The Ruby Sass and LibSass (C) compilers are no …
> Prepare 7.0.0 release

- CHANGELOG.md
- CONTRIBUTING.md
- docs/_includes/helpers/code-example.html
- test/screenshot.test.js
**Why?** So that it'll continue to work after the main design.login.gov site is decommissioned.
Also updates a few other internal references to https://design.login.gov which would break after the site is taken offline.
> Run regression spec against preview site

- CHANGELOG.md
- docs/_components/side-navigation.md
- docs/_includes/nav/link-item.html
- docs/_includes/nav/page-item.html
- docs/_layouts/main.html
- package-lock.json
- package.json
- src/scss/packages/_usa-header.scss
- src/scss/packages/_usa-nav.scss
- src/scss/packages/_usa-section.scss
- src/scss/packages/_usa-sidenav.scss
This resolves a regression introduced as part of the changes in the 7.0.0 release where the "current" link would be shown with a blue underline instead of a red underline.
Example from https://design.login.gov/brand/ :
Compare to https://login.gov/what-is-login/ :
After discussing with @nickttng , the changes here are a bit more of an extensive "reset" to USWDS stock styling, with minimal overrides to apply expected customizations:
- Remove bold text styling from links other than the current header navigation linik
- Change bar underline from blue ("primary" token) to red ("secondary" token)
- Reduce horizontal padding between header navigation items from 2rem (32px) to 1.5rem (24px)
- Reduce margins of logo
- Increase vertical padding of side navigation and mobile navigation items from …
> Fix header navigation current link styling regression

- .stylelintrc.json
- gulpfile.js
- src/scss/uswds-packages
**Why?**
- Simpler
- We don't need it, we can point directly to node_modules for the only place we use it now (Sass loadPaths)
- May have better cross-OS compatibility (i.e. Windows)
> Remove uswds-packages symlink

- CHANGELOG.md
- docs/_components/button-groups.md
- src/scss/packages/_usa-button-group.scss
- src/scss/packages/usa-button-group/src/_overrides.scss
- src/scss/packages/usa-button-group/src/_styles.scss
~Merges to (blocked by) #356~
**Why?** LGDS styles default button stroke width as 1px, and has custom styles to override stroke width to 2px for big buttons. USWDS button group styles use the stroke width, but are not aware of our customizations to double the width for big buttons, so we need to manually override these styles.
In practice, this makes a small difference on the appearance of a borders buttons.
Before|After
---|---
Live preview URL: https://federalist-340d8801-aa16-4df5-ad22-b1e3e731098e.sites.pages.cloud.gov/preview/18f/identity-design-system/aduth-button-groups-border/components/button-groups/
Related IdP usage: https://github.com/18F/identity-idp/pull/8542
LGDS big button customizations:
https://github.com/18F/identity-design-system/blob/1a488efdb6ff4ca1f0a05873440d60be93e …
> Improve styling for segmented "big" button group

- docs/_layouts/base.html
There have been some visual regression failures on recent pull requests related to content encoding (see https://github.com/18F/identity-design-system/pull/359#issuecomment-1585069144). Based on my understanding, it doesn't _seem_ like this tag should be necessary, as `utf-8` should already be the default for HTML5 documents. But it does appear to have a positive effect, where builds appear to be passing again (after 4 retries).
> Add meta charset to documentation layout to fix visual regressions tests

- CHANGELOG.md
- src/scss/packages/usa-process-list/src/_overrides.scss
~Merges to (blocked by) #356~
Fixes an issue where Process List "Big" variant would show with the connected line when not rendered in prose content.
Issue can be seen here ("Big" should not show line): https://idp.dev.identitysandbox.gov/components/inspect/process_list/preview
Issue can't be seen here, since design system documentation is shown in `.usa-prose`: https://design.login.gov/components/process-list/#big
The underlying issue is a CSS specificity conflict, where the styles responsible for [unsetting the border width](https://github.com/18F/identity-design-system/blob/76d17e736e7c446476e22246ce1230bbd37745db/src/scss/packages/_usa-process-list.scss#L11-L13) were only strong enough to override [the previous border width styling](https://github.com/18F/identity-design-system/blob/76d …
> Fix Process List "Big" variant showing connected line

- CHANGELOG.md
- package-lock.json
- package.json
🎫 Ticket
https://cm-jira.usa.gov/browse/LG-10861
❓ The Ask
@aduth Could you finish the release I started here? I don't yet have the correct npm access to run `npm publish`. I'm still working on that. `npm publish --dry-run` looks correct to me though.
💬 Changes
I'd like to release version `7.1.0` of the `identity-design-system`. This release contains all the work I can do (from [here](https://github.com/18F/identity-design-system/blob/a863995e7ffca82409645c15d34f0b979b6b1921/CONTRIBUTING.md#releases)) in that direction since I don't have the permissions to run `npm publish` in the 18f org on npm.
This PR contains:
- Changelog updates.
- A version number update from running `npm version minor`
- This PR is for an appropriately named release branch (7.1.0)
> Release Request: 7.1.0

- .github/dependabot.yml
- CHANGELOG.md
- gulpfile.js
- package-lock.json
- package.json
- src/js/components/index.js
- src/scss/packages/_uswds-core.scss
- src/scss/packages/usa-input/src/_overrides.scss
- src/scss/packages/usa-prose/src/_overrides.scss
Upgrades USWDS to its latest version, from 3.4.1 to 3.6.0.
Release notes:
- https://github.com/uswds/uswds/releases/tag/v3.5.0
- https://github.com/uswds/uswds/releases/tag/v3.6.0
Also updates `dependabot.yml` to change the dependency name (the npm package was [renamed from `uswds` to `@uswds/uswds`](https://designsystem.digital.gov/documentation/migration/#2-install-the-uswds-3-0-package) in v3.0.0), since the purpose of the configuration is to automate these updates.
~**Blocked:** There's a build issue that needs to be sorted out. Also reported upstream at https://github.com/uswds/uswds/issues/5334 .~ **Edit:** This is now fixed in USWDS 3.6.0.
> Upgrade USWDS from v3.4.1 to v3.6.0

- CHANGELOG.md
- src/scss/packages/_uswds-core.scss
**Why?** We don't currently use Serif fonts. Previously, we overrode the Serif font face configuration to set Public Sans. Instead, this proposes to _disable_ the serif font, and reconfigure the heading to use the Sans "role". This should be more semantically accurate, and optimizes the output to prevent [serif-related font utilities](https://designsystem.digital.gov/utilities/font-size-and-family/) from being output.
There should be no visual impact expected from these changes.
Related: https://github.com/18F/identity-idp/pull/9290
> Disable Serif fonts

- CHANGELOG.md
- package-lock.json
- package.json
> ### Breaking Changes
> 
> - Serif fonts are disabled by default. This should not have a noticeable impact in most cases, since the Serif fonts were already previously assigned to Public Sans (a Sans Serif font).
> - Update USWDS from 3.4.1 to 3.6.1
>   - See release notes:
>     - https://github.com/uswds/uswds/releases/tag/v3.5.0
>     - https://github.com/uswds/uswds/releases/tag/v3.6.0
>     - https://github.com/uswds/uswds/releases/tag/v3.6.1
>   - Note "Breaking" changes in the above minor releases. Additionally, the `inputPrefixSuffix` JavaScript named export has been removed.
> Prepare 8.0.0 release

- src/scss/packages/_uswds-core.scss
Small revision to #374 prior to releasing 8.0.0 version. I noticed in testing the release an error in `identity-idp` when trying to override this value. As you can see in all surrounding variables, we usually set `!default` flag to allow downstream projects to reconfigure any value from the design system, so that's introduced here for consistency to the variables configured in #374.
> Mark font role variables as default

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/packages/usa-accordion/src/_overrides.scss
Fixes an issue where the wrong icon appears when hovering the expanded or collapsed accordion button, due to specificity changes in USWDS.
Live preview: https://federalist-340d8801-aa16-4df5-ad22-b1e3e731098e.sites.pages.cloud.gov/preview/18f/identity-design-system/aduth-fix-accordion-expander/accordions/
State|Before|After
---|---|---
Expanded|![image](https://github.com/18F/identity-design-system/assets/1779930/a043bca6-d344-4af5-b2f6-c79b062e8b34)|![image](https://github.com/18F/identity-design-system/assets/1779930/b7cd78be-fdef-4dd5-87c4-235c21bfb188)
Collapsed|![image](https://github.com/18F/identity-design-system/assets/1779930/466b415e-e8ce-408f-8d34-f3a484063807)|![image](https://github.com/18F/identity-design-system/assets/1779930/3d2b0f73-2445-41b3-889d-5c8f568ebebb)
Unhovered, …
> Fix issue with wrong accordion icon when hovering the expander

- package-lock.json
- package.json
- test/accessibility.test.mjs
- test/screenshot.test.mjs
Replaces/consolidates [`serve-static`](https://www.npmjs.com/package/serve-static) as the static file server used within specs with [ESBuild](https://esbuild.github.io/).
In putting together #387, I noticed this as a listed feature of the project, which helps eliminate a necessary dependency introduced with #386.
**Why?**
- We already have the dependency available
- Reduces dependency tree depth (see lines removed), which helps maintainability by eliminating a common source of security advisories
- It results in slightly simpler code overall
```
make test
```
> Use ESBuild file server for specs

- docs/_includes/helpers/base-component.html
- docs/_plugins/file_exists.rb
Avoids showing a link to "View Login.gov SCSS on GitHub" for a component documentation page if there is no custom Sass styling for that component.
1. Go to https://federalist-340d8801-aa16-4df5-ad22-b1e3e731098e.sites.pages.cloud.gov/preview/18f/identity-design-system/aduth-docs-overrides-404/icon-list/
2. Observe there is no link for "View Login.gov SCSS on GitHub", since we don't customize the styles for this component
3. Compare to current main: https://federalist-340d8801-aa16-4df5-ad22-b1e3e731098e.sites.pages.cloud.gov/site/18f/identity-design-system/icon-list/
> Hide broken link for uncustomized components

- package-lock.json
- package.json
- test/accessibility.test.mjs
- test/screenshot.test.mjs
Modifies tests which run across all documentation pages in Puppeteer to use [the test runner's `concurrency` feature](https://nodejs.org/api/test.html#testname-options-fn) to parallelize individual pages.
Recommend reviewing with whitespace changes hidden: https://github.com/18F/identity-design-system/pull/389/files?w=1
**Why?**
- It should run generally faster ("Run visual regression test" in [27s](https://app.circleci.com/pipelines/github/18F/identity-design-system/1322/workflows/57bdb49b-bc29-4724-aefb-3196cbf82829/jobs/3660) vs. [49s](https://app.circleci.com/pipelines/github/18F/identity-design-system/1321/workflows/3cd6ea42-0048-4c35-916e-d1679c9a51f7/jobs/3656) as a single data point)
- Better scalability if we add or split new documentation pages (e.g. new components, or breaking …
> Add concurrency to browser integration tests

- Makefile
Fixes a regression of #385 (6da543a39c0eb215f901c3b76005f32f62a11693) which caused `npm start` to no longer compile JavaScript and Sass assets automatically due to the expectation that Makefile targets would be run in parallel. It does so by restoring parallelism in a subprocess for the `start` target.
1. Run `npm start`
2. Observe in the output: `npm run watch:docs`
> Fix Makefile start command parallelism

- README.md
Updates `README.md` usage example to simplify the Sass build command to avoid an unnecessary options flag.
`@18f/identity-build-sass` will automatically add the load path as of `@18f/identity-build-sass@1.2.0` (https://github.com/18F/identity-idp/pull/8346):
From [CHANGELOG.md](https://github.com/18F/identity-idp/blob/main/app/javascript/packages/build-sass/CHANGELOG.md#120):
>If `@18f/identity-design-system` is installed, `node_modules/@18f/identity-design-system/packages` is added as a load path.
Follow the usage instructions and verify there are no errors when running the given command.
> Remove unnecessary load-path from usage example

- CONTRIBUTING.md
Updates `CONTRIBUTING.md` to replace outdated documentation guidance with new guidance referencing the availability of branch preview documentation.
For context, we previously hosted public-facing documentation at https://design.login.gov , which was decommissioned (#333), and the documentation site repurposed for local development and review purposes (#358).
These content revisions avoid references to documentation updates triggered on `main` merges and instead highlights the availability of branch preview documentation sites.
Review the [documentation preview for revisions](https://github.com/18F/identity-design-system/blob/aduth-rm-docs-build-ref/CONTRIBUTING.md#branch-documentation-previews) and verify that the instructions make sense.
> Update CONTRIBUTING to reflect documentation availability

- CHANGELOG.md
- package-lock.json
- package.json
>## 8.1.0
>
>### New Features
>
>- Add variant support for danger outline buttons. ([#383](https://github.com/18F/identity-style-guide/pull/383))
>
>### Bug Fixes
>- Improve consistency with USWDS disabled buttons styles. ([#383](https://github.com/18F/identity-style-guide/pull/383))
>   - [USWDS v3.5.0](https://github.com/uswds/uswds/releases/tag/v3.5.0) removed `.usa-button--disabled` styling in favor of `[aria-disabled="true"]`. This wasn't documented as a breaking change, and it's expected the any `.usa-button--disabled` usage would not be stylized correctly since those changes. You should replace any usage of `usa-button--disabled` with either the `[disabled]` or `[aria-disabled="true"]` attributes.
>
>### Internal
>
>- The package is now distributed using native ES Modules as the …
> Prepare 8.1.0 release

- CHANGELOG.md
- src/js/index.js
Fixes a regression in #395 where using ES Modules requires imports to reference the full path of any file.
See: https://nodejs.org/api/esm.html#mandatory-file-extensions
Error after upgrading to `8.1.0` in `identity-site`:
```
ERROR in ./node_modules/@18f/identity-design-system/build/esm/index.js 1:0-29
Module not found: Error: Can't resolve './components' in '/Code/identity-site/node_modules/@18f/identity-design-system/build/esm'
Did you mean 'index.js'?
BREAKING CHANGE: The request './components' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory …
```
> Use fully-qualified path for components

- CHANGELOG.md
- package.json
Fixes another regression of #395, where downstream projects can resolve the CommonJS built output, but would treat its code as ES Modules, since the project's top-level `package.json` includes `"type": "module"`. It's unclear why this wouldn't have been an issue prior to #395.
Example failure: https://github.com/18F/identity-idp/pull/9992
Error:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Code/identity-idp/app/javascript/packages/clipboard-button/clipboard-button-element.spec.ts
```
I'm  not 100% about the solution here since typically a package would only contain a single, root-level `package.json`. However, I've tested to confirm that it works, and have seen the idea referenced in a few places:
- …
> Fix CommonJS import compatibility

- docs/_components/prose.md
- test/screenshot.test.js
Attempts to fix some test flakiness in visual regression specs, where links may sometimes be "visited" and appear in a purple color depending on test parallelism, since pages are now run concurrently across multiple tabs as of #389.
The solution is to use a Chrome Incognito (private browsing) context, where history will not be remembered. In my brief testing of a live Incognito tab, links will never show with visited styling.
Build should pass.
Test locally:
```
ONLY_VISUAL_REGRESSION_TEST=1 make test
```
> Use Incognito in visual regressions to avoid visited link styling

- .circleci/config.yml
- .eslintrc.json
- Makefile
- docs/_components/accordions.md
- scripts/snapshot.js
- test/screenshot.test.js
Updates visual regression testing to avoid reliance on a hosted copy of the "main" branch, in anticipation that we may need to decommission current hosted references.
Build should pass.
Test locally by generating "snapshot" on each of `main` and this branch (`aduth-internal-visual-regression`) before running visual regression test:
1. `git checkout main`
2. `git checkout aduth-internal-visual-regression -- scripts/snapshot.js`
3. `scripts/snapshot.js`
4. `rm scripts/snapshot.js`
5. `git checkout aduth-internal-visual-regression`
6. `scripts/snapshot.js`
7. `ONLY_VISUAL_REGRESSION_TEST=true make test`
> Run visual regression testing as self-contained without external hosting

- CHANGELOG.md
- docs/_components/icon-list.md
- src/scss/packages/_uswds-core.scss
Updates theme configuration to remove color palettes for anything other than "required", "theme", or "state", effectively removing ad hoc color usage (e.g. green) in favor of semantic color tokens (e.g. success).
**Why?**
- In almost all cases, the state colors are more semantic in representing the intent of the color
- The colors were wrong, since we weren't customizing the underlying [system colors](https://designsystem.digital.gov/design-tokens/color/system-tokens/), e.g. `text-green` was `#538200` vs. `text-success` as `#18852e`
- This was noticed by @Sgtpluck in https://github.com/18F/identity-dev-docs/pull/449
- Slight reduction in stylesheet size
> Remove raw color utilities

- docs/_components/image-example.md
Fixes the Image Example component documentation to include the BEM "block" class which the `usa-image-example--correct` modifier class is expected to modify.
**Why?**
- In case new default styles are added to all `usa-image-example` subvariants, the base class needs to be present
- This component code is often used as reference ([example](https://github.com/18F/identity-dev-docs/pull/449#discussion_r1478847456))
> Add missing BEM base class in Image Example component code

- CHANGELOG.md
- Makefile
- package-lock.json
- package.json
- src/js/auto.js
- src/js/components/index.js
- test/accessibility.test.js
- test/components/index.test.js
- test/screenshot.test.js
- tsconfig.json
- typings/uswds__uswds.d.ts
Adds TypeScript type-checking for existing JavaScript files.
As evidenced by the included changes, this helped highlight a couple legitimate issues:
- The test for ensuring all components are exported was not working as intended, and therefore there were several components not being exported
- The HTML_CodeSniffer test incorrectly assumed there would be an error argument passed in the callback, which doesn't exist
```
npm run typecheck
```
> Add TypeScript type-checking

- .circleci/config.yml
- scripts/snapshot.js
Adjusts continuous integration workflow to optimize visual regressions.
Specifically:
- Ensure that parallelized `page` are closed once completed to avoid memory leak
- Avoid using `networkidle0`, which effectively incurs a `sleep(500ms)` ([docs](https://pptr.dev/api/puppeteer.puppeteerlifecycleevent))
- Avoid unnecessary NPM package build and limit build to documentation site
- Parallelize tasks for building documentation site
- Avoid creating an Incognito browsing context, which seems to incur a noticeable start-up cost, and should hopefully not be necessary anymore with changes in #403 and https://github.com/18F/identity-design-system/pull/402#issuecomment-1915477963
On average, this should save upward of 10 seconds from the "visual_regression" workflow.
See `snapshot-branch` and …
> Optimize CI visual regression snapshotting

- CHANGELOG.md
- index.d.ts
- package-lock.json
- package.json
Includes TypeScript types in the published NPM package for JavaScript components.
This basically republishes `@uswds/uswds` DefinitelyTyped types, with corrected LGDS aliases and missing type definitions for newer components. There were a handful of different errors with the DefinitelyTyped types, and I may work to propose an upstream patch to resolve these, which would hopefully allow the typings of this package to be simplified.
This doesn't include enforcement that the typings exactly reflect the exported components, which I'd like to add in future iterations to provide similar guarantees to what's asserted in [`test/components/index.test.js`](https://github.com/18F/identity-design-system/blob/main/test/components/index.test.js).
I tested this in `identity-idp` by changing its …
> Add TypeScript types for JavaScript components

- CHANGELOG.md
- index.d.ts
- src/js/components/index.js
- test/components/index.test.js
Updates JavaScript components to ensure that their names match those exported by USWDS. This is an inconsistency within USWDS itself between its package directory names and the corresponding exported JavaScript component name.
**Why?**
- This package is meant to operate as a drop-in replacement for USWDS, so its exported members should match 1-to-1
Verify the modified test passes:
```
npm run build
node --test test/components/index.test.js
```
> Align JavaScript component names with USWDS

- scripts/snapshot.js
Increases the width for visual regression snapshots from the [default 800x600](https://pptr.dev/api/puppeteer.browserconnectoptions#properties) to 1024x768.
**Why?**
- 800x600 is a pretty non-typical size, and the updated size provides a more consistent desktop-like viewport
- This was most noticeable in screenshots produced by #418, where the "Menu" button continues to appear until at least 1024px width. Without this change, there's some redundancy in having both the "default" and "mobile" examples, since both would show the mobile "Menu" button
1. `make build`
2. `./scripts/snapshot.js`
3. Observe that files in `tmp/screenshot/branches/aduth-visual-regression-snapshot-width` have width 1024px
Using example from #418:
Before|After
---|---
> Increase viewport width for regression screenshots

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/auto.js
- test/imports.test.js
- tsconfig.json
Fixes an error which occurs when trying to load the `auto` entrypoint in a bundler which resolves ESM imports.
```
Module not found: Error: Can't resolve './components' in '/node_modules/@18f/identity-design-system/build/esm'
```
This is an identical issue as what was addressed in #400, but the earlier pull request only addressed the instance of the issue within `index.js`. This pull request applies the same fix to `auto.js`.
This issue was surfaced as part of ongoing work in https://github.com/18F/identity-dashboard/pull/748
Verify included test passes:
1. `make build`
2. `node --test test/imports.test.js`
Optionally, verify in an external project that you can reference `/auto`:
1. In `identity-design-system`, ensure everything is built: `make build`
2. In external project, modify …
> Fix error when importing from ESM auto entrypoint

- CHANGELOG.md
- src/scss/packages/usa-nav/src/_overrides.scss
Fixes an issue where an expanded navigation section will show incorrectly with a light background when hovered.
See: https://github.com/18F/identity-dashboard/pull/748#issuecomment-1977518011
The background color here is meant to apply for hover states within the mobile navigation, and should not apply for larger viewport sizes. The solution is to add a media query to prevent the color from applying beyond the mobile navigation viewport width.
1. Run `npm start`
2. Go to http://localhost:4000/header/
3. Click "Section" or "Current Section" to expand navigation items
4. Keep cursor hovered over the navigation item
5. Observe that it shows correctly with a dark-blue background and white foreground text
6. In the "Mobile" preview at the bottom of the page, hover over navigation items
7. …
> Fix active hover state for navigation section

- CHANGELOG.md
- package-lock.json
- package.json
> ## 9.0.0
> 
> ### Breaking Changes
> 
> - [Prose](https://designsystem.digital.gov/components/prose/) styling overrides have been removed. Text formatting should now adhere to the defaults from the U.S. Web Design System. ([#390](https://github.com/18F/identity-design-system/pull/390))
> - Drop support for Internet Explorer. ([#387](https://github.com/18F/identity-style-guide/pull/387))
>    - Support was indirectly dropped in [v7.0.0](https://github.com/18F/identity-design-system/releases/tag/v7.0.0) via the upgrade to USWDS [v3.0.0](https://designsystem.digital.gov/about/releases/#version-uswds-300), which similarly ended explicit support for Internet Explorer. This package had continued to include Internet Explorer in its [Browserslist](https://browsersl.ist/) configuration, but this …
> Prepare 9.0.0 release

- docs/_components/header.md
- docs/_embeds/header/mobile.md
Updates header component example source code to exclude `hidden` attributes.
These examples are meant to serve as reference implementations and therefore should be accurate.
The `hidden` attribute should not be included so that the menu sections appears as expanded on devices where JavaScript is disabled. The design system JavaScript will dynamically add back the `hidden` attribute, and when used in combination with the `init.js` initializer script, no flashing content should occur.
Verify there is no regression in the appearance of section navigation menus in the Header component example.
1. `npm start`
2. Go to http://localhost:4000/header/
> Remove hidden attributes from header component code

- CHANGELOG.md
- src/scss/packages/usa-tag/src/_overrides.scss
Removes some styling overrides from the Tag component for consistency with USWDS:
- Remove border radius override, reducing radius from 0.25rem (4px) to 0.125rem (2px)
- Remove bold styling override, reverting to normal font size
1. Run the application locally: `npm start`
2. Go to http://localhost:4000/tags/
3. Observe visual appearance of tags
Before|After
---|---
> Update styling for Tag component for consistency with USWDS

- docs/_components/header.md
Improves header component markup example to avoid `<div class="usa-nav-container">`. It also updates the logo link to always point to the root regardless of `{{ site.baseurl }}` value (previously it would often link to the same page).
**Why?**
- This markup was originally sourced from `identity-site`, but the [default USWDS component guidance](https://designsystem.digital.gov/components/header/) for extended header does not include it
- The `usa-nav-container` creates additional horizontal padding that causes it to be misaligned with page content that includes navigation
Easiest to review with whitespace changes hidden, since the changes amount to removing a single wrapper element `<div class="usa-nav-container">`.
1. `npm start`
2. Visit http://localhost:4000/banner/
3. Observe reduced …
> Remove nav container from header component example

- _config.yml
- docs/_includes/banner.html
- docs/_includes/header.html
- docs/_layouts/base.html
- docs/_layouts/component.html
Adds banner, header, and primary navigation to the local documentation site.
**Why?**
- "Dogfooding" our own components helps surface potential issues with documented usage (see #429 and #430 as examples)
- This also opens the possibility of internally reusing "includes" for header with documented usage for guaranteed one-to-one documentation and usage
- This is part of a series of changes looking to introduce new sections for "Utilities" in addition to components, which will be included in the primary navigation.
1. Go to http://localhost:4000
2. Observe banner, header, and primary navigation
Before|After
---|---
> Add banner and header with navigation

- CHANGELOG.md
- docs/_components/accordions.md
- docs/_components/validation.md
- docs/_includes/helpers/code-example.html
- src/js/init.ts
- src/scss/packages/usa-accordion/src/_overrides.scss
This enhances accordion styles to appear hidden while JavaScript is loaded if expected to be collapsed once JavaScript finishes loading, avoiding the appearance of flashing content.
This backports changes added to the brochure site in https://github.com/GSA-TTS/identity-site/pull/1224
It also incorporates a number of improvements:
- Fixes an issue with https://github.com/GSA-TTS/identity-site/pull/1224 where it would not apply to sibling content of accordions where the button is wrapped inside a header container
- Inverts the selector to look for `:not([aria-expanded='true'])` instead of `[aria-expanded='false']` to support expected behavior where the `aria-expanded` attribute is not explicitly specified
- Updates component examples for Accordion:
- Document differences between "Default" …
> Hide collapsed Accordion component content while JavaScript loads

- package.json
Updates JavaScript build script to perform the rename of `auto.js` source script to `main.js` dist script as part of the ESBuild command itself, using [custom output path support](https://esbuild.github.io/api/#entry-points:~:text=In%20addition%2C%20you%20can%20also%20specify%20a,Go).
This is both simpler, and will hopefully address some inconsistent issues where the post-build script isn't always run as expected, resulting in a scenario where `main.js` 404s.
1. `npm start`
2. Visit http://localhost:4000
3. Observe no errors in the developer tools console, and script loading works as expected (e.g. banner is not expanded by default)
> Assign script output name in ESBuild command

- CHANGELOG.md
- src/scss/packages/usa-error-message/src/_overrides.scss
- src/scss/packages/usa-success-message/src/_styles.scss
Updates validation messages (`.usa-error-message`, `.usa-success-message`) to use USWDS icons.
This works toward removing our custom alert icons in favor of USWDS icons.
Related: https://github.com/18F/identity-design-system/pull/439, https://github.com/18F/identity-design-system/pull/442
1. Run locally as `npm start`
2. Go to http://localhost:4000/validation/
3. Observe validation messages
Before|After
---|---
> Use USWDS icons with validation messages

- test/screenshot.test.js
This pull request:
- Updates Puppeteer to the latest version
- Removes resize handling in visual regression specs
The intent is to try to resolve inconsistencies observed in visual regression failures in #437:
- As noted at https://github.com/18F/identity-design-system/pull/437#issuecomment-2069224563, the `fillImageToSize` helper doesn't work as intended, since it will only fill pixels which are missing outside both the expected width and height, but not either lacking height nor lacking width.
- Ideally we don't want to tolerate any difference in dimensions. By git history, it's not entirely clear why this was added.
- In local testing, it seems that updating Puppeteer does have an impact in allowing the visual regression spec to pass, which could be due to differences in Chromium …
> Update Puppeteer, remove resize handling in visual regression specs

- CHANGELOG.md
- src/scss/packages/usa-verification-badge/src/_styles.scss
Iterates on styles introduced in #442 targeting the badge icon.
The IdP has a [novel implementation](https://github.com/18F/identity-idp/pull/10065) of icon component which does not render markup as an `<svg />` element, but _does_ implement the equivalent as with the `usa-icon` class. Since it would be preferable (more precise) to implement the class selector vs. an element selector, this improves compatibility as well as improving the general implementation.
As part of the changes here, I dropped the selector which was deprecated as part of the work in #442, with the expectation this can be included in the next major release.
A patch release is not planned, and a temporary workaround will be added to the IdP instead.
Repeat testing plan from #442.
There is not expected to be any visual …
> Improve compatibility/precision for badge styles

- CHANGELOG.md
- docs/_components/alerts.md
- src/scss/packages/usa-alert/src/_overrides.scss
Updates the Alert component styles to eliminate the custom `usa-alert--other` styles. This is intended to be backwards-compatible, where "Other" is intended to represent a stateless alert banner. This is already styled through USWDS as a slightly different shade of gray, and these changes help remove some confusion and extra code.
The concept of an "other" or default variant is already inherent to the idea of a BEM class "**B**lock", so it's redundant to have an explicit class. Technically it was already possible to use these styles with a `<div class="usa-alert">`, though it was never documented.
1. Go to http://localhost:4000/alerts/
2. Observe "Default" alert styles
Before|After
---|---
> Update default alert styles to replace "Other" variant
